all:
	chmod +x ../MakeFiles/make3Sat.sh
	chmod +x ../MakeFiles/make3SatToCol.sh
	chmod +x ../MakeFiles/makeColToSat.sh
	cp ../MakeFiles/make3Sat.sh sattothreesat
	cp ../MakeFiles/make3SatToCol.sh threesattocol
	cp ../MakeFiles/makeColToSat.sh coltosat
	chmod +x sattothreesat
	chmod +x coltosat
	chmod +x threesattocol

clean:
	rm sattothreesat
	rm coltosat
	rm threesattocol
	rm threesattothreecol
